"""2.0.8

Revision ID: f74adc9e2cf4
Revises: eaf9cbc49027
Create Date: 2024-11-17 20:27:29.368028

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'f74adc9e2cf4'
down_revision = 'eaf9cbc49027'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('downloadhistory', sa.Column('monitor_type', sa.String(), nullable=True))
    op.add_column('subscribe', sa.Column('monitor_type', sa.String(), nullable=True))
    op.add_column('transferhistory', sa.Column('monitor_type', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transferhistory', 'monitor_type')
    op.drop_column('subscribe', 'monitor_type')
    op.drop_column('downloadhistory', 'monitor_type')
    # ### end Alembic commands ###
